name: "Paths-filter test"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, closed]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'src/**'

  nochange:
    name: File no change
    needs: paths-filter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if file has not changed
        run: |
          sh ./test_nochange.sh
  change:
    name: File change
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if file has changed
        run: |
          sh ./test.sh
