name: "Paths-filter test"
on:
  pull_request:
    branches:
      - "master"
    types: [opened, synchronize, closed]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
    - uses: dorny/paths-filter@v2
    - uses: actions/checkout@v2
      id: filter
      with:
        filters: |
          src:
            - 'src/**'

  nochange:
    name: File no change
    runs-on: ubuntu-latest
    steps:
    - name: Check if file has not changed
      run: |
        ./test-nochange.sh
  change:
    name: File no change
    runs-on: ubuntu-latest
    - if: ${{ needs.changes.outputs.src == 'true' }}
      run: |
        ./test.sh
